server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  charset utf-8;
  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml text/markdown;
  location ~* \.md$ { default_type "text/markdown; charset=utf-8"; }
  location ~* \.(woff2|webp|png|svg|ico)$ { expires 30d; }
}
